//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoresService
{
    using System;
    using System.Collections.Generic;
    
    public partial class BETS_MATCHES
    {
        public int ID { get; set; }
        public int ID_BET { get; set; }
        public int ID_MATCH { get; set; }
        public int TYPE { get; set; }
    }
}
