//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoresService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCORESEntities : DbContext
    {
        public SCORESEntities()
            : base("name=SCORESEntities")
        {
            AutoMapper.Mapper.CreateMap<MATCH, Common.DataContracts.MATCH>();
            AutoMapper.Mapper.CreateMap<Common.DataContracts.MATCH, MATCH>();

            AutoMapper.Mapper.CreateMap<Common.DataContracts.USER_MATCH, USER_MATCH>();
            AutoMapper.Mapper.CreateMap<USER_MATCH, Common.DataContracts.USER_MATCH>();

            AutoMapper.Mapper.CreateMap<Common.DataContracts.BET, BETS>();
            AutoMapper.Mapper.CreateMap<BETS, Common.DataContracts.BET>();

            AutoMapper.Mapper.CreateMap<Common.DataContracts.BETS_MATCHES, BETS_MATCHES>();
            AutoMapper.Mapper.CreateMap<BETS_MATCHES, Common.DataContracts.BETS_MATCHES>();

            AutoMapper.Mapper.CreateMap<Common.DataContracts.LEAGUE, LEAGUE>();
            AutoMapper.Mapper.CreateMap<LEAGUE, Common.DataContracts.LEAGUE>();

            AutoMapper.Mapper.CreateMap<Common.DataContracts.TEAM, TEAM>();
            AutoMapper.Mapper.CreateMap<TEAM, Common.DataContracts.TEAM>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<USER_MATCH> USER_MATCH { get; set; }
        public virtual DbSet<BETS> BETS { get; set; }
        public virtual DbSet<BETS_MATCHES> BETS_MATCHES { get; set; }
        public virtual DbSet<LEAGUE> LEAGUE { get; set; }
        public virtual DbSet<MATCH> MATCH { get; set; }
        public virtual DbSet<TEAM> TEAM { get; set; }
    }
}