//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoresService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAM
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public int ID_LEAGUE { get; set; }
        public int POINTS { get; set; }
        public int WIN { get; set; }
        public int DRAW { get; set; }
        public int LOSE { get; set; }
        public int GOAL_SCORED { get; set; }
        public int GOAL_CONCEDED { get; set; }
    }
}
